///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RX_coDiagnostiX_Library._Miscellaneous
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AcceptAlphaVersion recording.
    /// </summary>
    [TestModule("78cf29df-4479-4a75-8c1a-a95dd9daaf06", ModuleType.Recording, 1)]
    public partial class AcceptAlphaVersion : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RX_coDiagnostiX_Library.RX_coDiagnostiXRepository repository.
        /// </summary>
        public static global::RX_coDiagnostiX_Library.RX_coDiagnostiXRepository repo = global::RX_coDiagnostiX_Library.RX_coDiagnostiXRepository.Instance;

        static AcceptAlphaVersion instance = new AcceptAlphaVersion();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AcceptAlphaVersion()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AcceptAlphaVersion Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nWaiting 10s to exist. Associated repository item: 'BetaBox'", repo.BetaBox.SelfInfo, new ActionTimeout(10000), new RecordItemIndex(0));
                repo.BetaBox.SelfInfo.WaitForExists(10000);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'BetaBox.IAcceptTheseTerms' at Center.", repo.BetaBox.IAcceptTheseTermsInfo, new RecordItemIndex(1));
                repo.BetaBox.IAcceptTheseTerms.Click();
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'BetaBox.ButtonStart' at Center.", repo.BetaBox.ButtonStartInfo, new RecordItemIndex(2));
                repo.BetaBox.ButtonStart.Click();
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
