///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RX_coDiagnostiX_Library.DiagnostiXModul.NewPlan
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NewPlanClickOk recording.
    /// </summary>
    [TestModule("29ec0d16-234f-4750-846c-a7de38d6b217", ModuleType.Recording, 1)]
    public partial class NewPlanClickOk : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::RX_coDiagnostiX_Library.RX_coDiagnostiXRepository repository.
        /// </summary>
        public static global::RX_coDiagnostiX_Library.RX_coDiagnostiXRepository repo = global::RX_coDiagnostiX_Library.RX_coDiagnostiXRepository.Instance;

        static NewPlanClickOk instance = new NewPlanClickOk();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NewPlanClickOk()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NewPlanClickOk Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'Forms.frmNewPlan'", repo.Forms.frmNewPlan.SelfInfo, new ActionTimeout(5000), new RecordItemIndex(0));
            repo.Forms.frmNewPlan.SelfInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Forms.frmNewPlan.ButtonOK' at Center.", repo.Forms.frmNewPlan.ButtonOKInfo, new RecordItemIndex(1));
            repo.Forms.frmNewPlan.ButtonOK.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
